In [2]:
%pip install torch

  Using cached torch-2.12.1-cp314-cp314-macosx_14_0_arm64.whl.metadata (31 kB)
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached torch-2.12.1-cp314-cp314-macosx_14_0_arm64.whl (88.0 MB)
Using cached setuptools-81.0.0-py3-none-any.whl (1.1 MB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [torch]32m5/6 [torch]kx]s]
Note: you may need to restart the kernel to use updated packages.


In [3]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

In [5]:
b = torch.tensor([[1,2] , [3,4]])
array_data = np.array([1,2,3,4])


In [6]:
e = torch.rand(2, 2)
print(e)

tensor([[0.2189, 0.1955],
        [0.3197, 0.2837]])


In [7]:
a = torch.tensor([[1,2], [3,4], [5,6]])
b = torch.rand(3,2)

c = a + b

print("a", a)
print("b", b)
print("c", c)
     

a tensor([[1, 2],
        [3, 4],
        [5, 6]])
b tensor([[0.1664, 0.2872],
        [0.5703, 0.5776],
        [0.2318, 0.3795]])
c tensor([[1.1664, 2.2872],
        [3.5703, 4.5776],
        [5.2318, 6.3795]])


In [8]:
d = a * b
print(d)


tensor([[0.1664, 0.5743],
        [1.7110, 2.3105],
        [1.1590, 2.2771]])


In [13]:
e  = torch.arange(6)

print(e.view(2,3))

tensor([[0, 1, 2],
        [3, 4, 5]])


In [14]:
x = torch.arange(16)
x = x.view(2, 2, 4)
print(x)
print(x.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]]])
torch.Size([2, 2, 4])


In [15]:
print(x[0])
print(x[:, 0])
print(x[:,:,0])
print(x[:,:,1:3])
     

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])
tensor([[ 0,  4],
        [ 8, 12]])
tensor([[[ 1,  2],
         [ 5,  6]],

        [[ 9, 10],
         [13, 14]]])


In [17]:
x = torch.tensor([2.0, 3.0])
x.requires_grad

x.requires_grad_(True)
print(x.requires_grad)

y = torch.tensor([3.0, 4.0], requires_grad=True)
print(y.requires_grad)
     

True
True


In [18]:
z = x + y
print(z)

z = x * y
print(z)

z = x ** 2
print(z)

z = x.mean()
print(z)

tensor([5., 7.], grad_fn=<AddBackward0>)
tensor([ 6., 12.], grad_fn=<MulBackward0>)
tensor([4., 9.], grad_fn=<PowBackward0>)
tensor(2.5000, grad_fn=<MeanBackward0>)


In [19]:
x = torch.tensor([2.0, 3.0], requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 3
z = z.mean()
print(z)

z.backward() # dz/dx
print("Gradients of z with respect to x: ", x.grad)

tensor([2., 3.], requires_grad=True)
tensor([4., 5.], grad_fn=<AddBackward0>)
tensor(61.5000, grad_fn=<MeanBackward0>)
Gradients of z with respect to x:  tensor([12., 15.])


In [21]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print(device)
     

cpu


In [23]:
import torch

# Verificăm suportul pentru NVIDIA, apoi Apple Silicon, apoi fallback pe CPU
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps")
else:
    device = torch.device("cpu")

print(f"Calculele vor rula pe: {device}")

Calculele vor rula pe: mps


In [24]:
# Dummy dataset
x = torch.tensor([1,2,3,4,5], dtype=torch.float32)
y = torch.tensor([2,4,6,8,10], dtype=torch.float32)

In [25]:
# Hyperparameters
learning_rate = 0.01
epochs = 100

In [28]:
import andom as rand

ModuleNotFoundError: No module named 'Random'

In [27]:
weights = torch.tensor(rand(1,1), requires_grad=True)

# Define forward function for linear model
def forward(x):
  return weights * x

NameError: name 'rand' is not defined